version: '3'

services:
  django:
    build: .
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --no-input --clear &&
                    gunicorn NewsTest.wsgi:application --bind 127.0.0.1:8000"
    env_file:
      - .env
    depends_on:
      - database_db
    expose:
      - 8000
    volumes:
      - ./NewsTest:/NewsTest/ # возможно переделать
      - staticfiles:/NewsTest/static/ # возможно переделать
  database_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
  nginx:
    build: nginx
    ports:
      - 1337:80
    volumes:
      - staticfiles:/NewsTest/static/
    depends_on:
      - django
volumes:
  postgres_data:
  staticfiles:

