# Generated by Django 3.1.6 on 2021-02-11 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.CharField(max_length=35)),
                ('publication_date', models.DateTimeField(default=datetime.datetime(2021, 2, 11, 13, 34, 35, 605511, tzinfo=utc))),
                ('body_news', models.TextField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='news')),
            ],
        ),
    ]
