# Generated by Django 3.1.6 on 2021-02-11 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 13, 35, 4, 140206, tzinfo=utc)),
        ),
    ]
