# Generated by Django 3.1.6 on 2021-02-12 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTape', '0003_auto_20210212_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body_news',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 12, 14, 17, 41, 491556, tzinfo=utc)),
        ),
    ]
