# Generated by Django 3.1.6 on 2021-02-14 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTape', '0004_auto_20210212_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 15, 5, 8, 20890, tzinfo=utc)),
        ),
    ]
