# Generated by Django 3.1.6 on 2021-03-07 03:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTape', '0005_auto_20210214_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 3, 0, 20, 486115, tzinfo=utc)),
        ),
    ]
